### ISSUE TITLE
DLL load failed ? Tensor flow error ?

### ISSUE THREAD

**Issue by evroscchristodoulou** [SkBlaz/tax2vec#6]
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by SkBlaz** [comment]
Hey @evroscchristodoulou , I've created a new conda env from scratch, see:
https://github.com/SkBlaz/tax2vec#prerequisites

Installing this _de novo_  works fine for me. Could you try too?

**Comment by evroscchristodoulou** [comment]
Here what I get after doing pip install -r requirements.txt & conda install
--yes --file requirements.txt.after doing I can see problem with libraries
but all of the are up to date.



conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - dbus==1.13.16=hb2f20db_0
  - pyqt==5.9.2=py38h05f1152_4
  - pandas==1.1.1=py38he6710b0_0
  - cython-blis==0.4.1=py38h7b6447c_1
  - libgfortran-ng==7.3.0=hdf63c60_0
  - cython==0.29.21=py38he6710b0_0
  - openssl==1.1.1h=h7b6447c_0
  - grpcio==1.31.0=py38hf8bcb03_0
  - cryptography==3.1=py38h1ba5d50_0
  - spacy==2.3.2=py38hfd86e86_0
  - libgcc-ng==9.1.0=hdf63c60_0
  - tensorflow-base==2.2.0=mkl_py38h5059a2d_0
  - numpy-base==1.19.1=py38hfa32c7d_0
  - freetype==2.10.2=h5ab3b9f_0
  - libtiff==4.1.0=h2733197_1
  - c-ares==1.16.1=h7b6447c_0
  - tk==8.6.10=hbc83047_0
  - pcre==8.44=he6710b0_0
  - matplotlib-base==3.3.1=py38h817c723_0
  - regex==2020.7.14=py38h7b6447c_0
  - ld_impl_linux-64==2.33.1=h53a641e_7
  - readline==8.0=h7b6447c_0
  - cymem==2.0.3=py38he6710b0_0
  - kiwisolver==1.2.0=py38hfd86e86_0
  - tensorflow==2.2.0=mkl_py38h6d3daf0_0
  - python==3.8.5=h7579374_1
  - zlib==1.2.11=h7b6447c_3
  - lz4-c==1.9.2=he6710b0_1
  - libxml2==2.9.10=he19cac6_1
  - tornado==6.0.4=py38h7b6447c_1
  - libstdcxx-ng==9.1.0=hdf63c60_0
  - lcms2==2.11=h396b838_0
  - jpeg==9b=h024ee3a_2
  - libxcb==1.14=h7b6447c_0
  - wrapt==1.12.1=py38h7b6447c_1
  - libuuid==1.0.3=h1bed415_2
  - mkl_random==1.1.1=py38h0573a6f_0
  - mkl-service==2.3.0=py38he904b0f_0
  - numpy==1.19.1=py38hbc911f0_0
  - cffi==1.14.3=py38he30daa8_0
  - protobuf==3.12.4=py38he6710b0_0
  - qt==5.9.7=h5867ecd_1
  - fontconfig==2.13.0=h9420a91_0
  - libpng==1.6.37=hbc83047_0
  - libprotobuf==3.12.4=hd408876_0
  - libffi==3.3=he6710b0_2
  - xz==5.2.5=h7b6447c_0
  - h5py==2.10.0=py38hd6299e0_1
  - gstreamer==1.14.0=hb31296c_0
  - murmurhash==1.0.2=py38he6710b0_0
  - sqlite==3.33.0=h62c20be_0
  - icu==58.2=he6710b0_3
  - scikit-learn==0.23.2=py38h0573a6f_0
  - preshed==3.0.2=py38he6710b0_1
  - hdf5==1.10.6=hb1b8bf9_0
  - thinc==7.4.1=py38hfd86e86_0
  - scipy==1.5.2=py38h0b6359f_0
  - srsly==1.0.2=py38he6710b0_0
  - glib==2.65.0=h3eb4bd4_0
  - gst-plugins-base==1.14.0=hbbd80ab_1
  - pyrsistent==0.17.3=py38h7b6447c_0
  - expat==2.2.9=he6710b0_2
  - sip==4.19.13=py38he6710b0_0
  - pillow==7.2.0=py38hb39fc2d_0
  - libedit==3.1.20191231=h14c3975_1
  - mkl_fft==1.2.0=py38h23d657b_0
  - zstd==1.4.5=h9ceee32_0
  - brotlipy==0.7.0=py38h7b6447c_1000
  - ncurses==6.2=he6710b0_1

**Comment by SkBlaz** [comment]
Interesting. Could you try one more thing; create  a new conda env, and
then:
conda install pip, followed by (in tax2vec folder) pip install -r
requirements.txt.

if this doesn't work, you can try to remove version numbers from the
libraries in the requirements folder (e.g., tensorflow>=1.13 -> tensorflow)

**Comment by evroscchristodoulou** [comment]
Hi different error, I think it's about a module
The co responding error from tensorflow
https://github.com/tensorflow/tensorflow/issues/22512


    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal:
The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by SkBlaz** [comment]
This seems to me like a tensorflow problem though. Are you able to install tensorflow as such?

**Comment by evroscchristodoulou** [comment]
Are you using CUDA and GPU for the taxonomy analysis ?

**Comment by SkBlaz** [comment]
no, the  BoW part from tf is used. You dont need cuda.

**Comment by SkBlaz** [comment]
Have you solved the tf part? I've tested on a windows machine and it seems to work ok ..

**Comment by evroscchristodoulou** [comment]
Yes everything works fine now. I did some reinstallments to my libraries.

Thank you !

**Comment by SkBlaz** [comment]
Great, thanks for the info!
